#!/usr/bin/env bash
# supervise.sh — PID1-style supervisor inside the container (no host cron/systemd)
# - optional supercronic schedule for mup (madrugada)
# - optional mup on boot
# - runs orca serve as child; restarts it when mup marks orca-restart-needed
set -euo pipefail

log() { printf '[supervise] %s\n' "$*"; }

HOME="${HOME:-/home/orca}"
export HOME
export PATH="${HOME}/.local/bin:${HOME}/.local/share/mise/shims:/usr/local/bin:/scripts:${PATH}"
export ORCA_INSTALL_DIR="${ORCA_INSTALL_DIR:-${HOME}/.local/share/orca}"
export LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-1}"

STATE_DIR="${HOME}/.local/state/orca-agent-manager"
RESTART_FLAG="${STATE_DIR}/orca-restart-needed"
mkdir -p "${STATE_DIR}"

ORCA_PORT="${ORCA_PORT:-6768}"
PAIRING_ARGS=()
if [[ -n "${ORCA_PAIRING_ADDRESS:-}" ]]; then
  PAIRING_ARGS+=(--pairing-address "${ORCA_PAIRING_ADDRESS}")
elif [[ -n "${TAILSCALE_HOSTNAME:-}" ]]; then
  PAIRING_ARGS+=(--pairing-address "${TAILSCALE_HOSTNAME}")
fi

truthy() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

ORCA_PID=""
CRON_PID=""

cleanup() {
  log "signal received — shutting down"
  if [[ -n "${CRON_PID}" ]] && kill -0 "${CRON_PID}" 2>/dev/null; then
    kill "${CRON_PID}" 2>/dev/null || true
  fi
  if [[ -n "${ORCA_PID}" ]] && kill -0 "${ORCA_PID}" 2>/dev/null; then
    kill "${ORCA_PID}" 2>/dev/null || true
    wait "${ORCA_PID}" 2>/dev/null || true
  fi
  exit 0
}
trap cleanup SIGTERM SIGINT SIGHUP

start_scheduler() {
  if ! truthy "${MUP_SCHEDULE:-true}"; then
    log "MUP_SCHEDULE=false — in-container cron disabled"
    return 0
  fi
  if ! command -v supercronic >/dev/null 2>&1; then
    log "WARN: supercronic not installed — schedule disabled"
    return 0
  fi

  local crontab="${MUP_CRONTAB_FILE:-/opt/orca-server/mup.crontab}"
  local runtime_cron="${STATE_DIR}/mup.crontab"
  mkdir -p "${STATE_DIR}"

  # Allow override of schedule via env without rebuilding
  # MUP_CRON default: 15 4 * * *  (04:15 every day, container local TZ)
  local expr="${MUP_CRON:-15 4 * * *}"
  {
    echo "# generated by supervise — do not edit by hand; set MUP_CRON / MUP_ON_BOOT"
    echo "SHELL=/bin/bash"
    echo "PATH=${PATH}"
    echo "HOME=${HOME}"
    echo "ORCA_VERSION=${ORCA_VERSION:-latest}"
    echo "ORCA_INSTALL_DIR=${ORCA_INSTALL_DIR}"
    echo "${expr} /scripts/mup.sh >>${STATE_DIR}/mup-cron.log 2>&1"
  } >"${runtime_cron}"

  # Optional: also keep a shipped reference crontab
  if [[ -f "${crontab}" ]]; then
    log "Reference crontab: ${crontab}"
  fi

  log "Starting supercronic — schedule '${expr}' (TZ=${TZ:-UTC})"
  supercronic -passthrough-logs "${runtime_cron}" >>"${STATE_DIR}/supercronic.log" 2>&1 &
  CRON_PID=$!
  log "supercronic pid=${CRON_PID}"
}

run_boot_mup() {
  if truthy "${MUP_ON_BOOT:-false}" || truthy "${AUTO_UPDATE_ALL:-false}"; then
    log "MUP_ON_BOOT — running mup before first orca start"
    /scripts/mup.sh || log "WARN: boot mup failed (non-fatal)"
  elif truthy "${AUTO_UPDATE_ORCA:-false}"; then
    /scripts/update-orca.sh "${ORCA_VERSION:-latest}" || log "WARN: orca update failed"
  elif truthy "${AUTO_UPDATE_AGENTS:-false}"; then
    /scripts/update-agents.sh || log "WARN: agents update failed"
  fi
}

start_orca() {
  log "Starting orca serve --port ${ORCA_PORT} ${PAIRING_ARGS[*]:-}"
  orca serve --port "${ORCA_PORT}" ${PAIRING_ARGS[@]+"${PAIRING_ARGS[@]}"} &
  ORCA_PID=$!
  log "orca pid=${ORCA_PID}"
}

stop_orca() {
  if [[ -n "${ORCA_PID}" ]] && kill -0 "${ORCA_PID}" 2>/dev/null; then
    log "Stopping orca pid=${ORCA_PID}"
    kill "${ORCA_PID}" 2>/dev/null || true
    # wait up to 25s
    for _ in $(seq 1 50); do
      kill -0 "${ORCA_PID}" 2>/dev/null || break
      sleep 0.5
    done
    kill -9 "${ORCA_PID}" 2>/dev/null || true
    wait "${ORCA_PID}" 2>/dev/null || true
  fi
  ORCA_PID=""
}

# --- main loop ---
start_scheduler
run_boot_mup

while true; do
  rm -f "${RESTART_FLAG}"
  start_orca

  # Watch child + restart flag
  while true; do
    if [[ -n "${ORCA_PID}" ]] && ! kill -0 "${ORCA_PID}" 2>/dev/null; then
      wait "${ORCA_PID}" 2>/dev/null || rc=$?
      rc="${rc:-0}"
      log "orca exited rc=${rc}"
      # Official: exit 3 = profile in use — don't tight-loop
      if [[ "${rc}" -eq 3 ]]; then
        log "exit 3 (profile in use) — backing off 30s"
        sleep 30
      else
        sleep 2
      fi
      ORCA_PID=""
      break
    fi

    if [[ -f "${RESTART_FLAG}" ]]; then
      log "orca-restart-needed flag set (mup upgraded binary) — recycling orca"
      stop_orca
      rm -f "${RESTART_FLAG}"
      break
    fi

    sleep 3
  done
done
